# TODO CBR: 每次发版前检查模块版本号
# 版本号在.env文件中定义

services:
  xianlai-gateway:
    image: wyatt6/xianlai-gateway:${XIANLAI_GATEWAY_VERSION}
    container_name: xianlai-gateway
    restart: on-failure:5
    volumes:
      - ./xianlai-gateway/application-run.yml:/app/application-run.yml:rw
      - ./xianlai-gateway/log:/app/log:rw
    networks:
      - xianlai_net
    ports:
      - "30000:30000"

  xianlai-system:
    image: wyatt6/xianlai-system:${XIANLAI_SYSTEM_VERSION}
    container_name: xianlai-system
    restart: on-failure:5
    volumes:
      - ./xianlai-system/application-run.yml:/app/application-run.yml:rw
      - ./xianlai-system/log:/app/log:rw
    networks:
      - xianlai_net
    ports:
      - "30001:30001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:30001/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  xianlai-mod-toolkit:
    image: wyatt6/xianlai-mod-toolkit:${XIANLAI_MOD_TOOLKIT_VERSION}
    container_name: xianlai-mod-toolkit
    restart: on-failure:5
    volumes:
      - ./xianlai-mod-toolkit/application-run.yml:/app/application-run.yml:rw
      - ./xianlai-mod-toolkit/log:/app/log:rw
    networks:
      - xianlai_net
    ports:
      - "30003:30003"
    depends_on:
      xianlai-system:
        condition: service_healthy

networks:
  xianlai_net:
    external: true
