datasource:
  redis:
    host: ???
    port: ???
    password: ???
    database: ???
#    lettuce.pool:                                             # Lettuce连接池配置（可选）
#      min-idle: 1                                             # 最小空闲连接数
#      max-idle: 10                                            # 最大空闲连接数
#      max-total: 10                                           # 最大连接数
#      max-wait: -1                                            # 最大等待时间（ms），-1表示最大
